# Source: jxboot-helmfile-resources/templates/maven-settings-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: vault-infra
  data:
  - name: settings.xml
    key: secret/data/jenkins/maven/settings
    property: settings.xml
  - name: settings-security.xml
    key: secret/data/jenkins/maven/settings
    property: settings-security.xml
  template:
    type: Opaque
