# Source: nexus/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus
  annotations:
    expose.config.fabric8.io/path-key: context.path
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
data:
  context.path: /
