apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: lighthouse-hmac-token
    mappings:
    - name: hmac
      key: secret/data/lighthouse/hmac
      property: token
  - name: lighthouse-oauth-token
    mappings:
    - name: oauth
      key: secret/data/jx/pipelineUser
      property: token
  - name: lighthouse-oauth-token
    mappings:
    - name: oauth
      key: secret/data/jx/pipelineUser
      property: token
  - name: nexus
    mappings:
    - name: password
      key: secret/data/jx/adminUser
      property: password
  - name: chartmuseum-chartmuseum
    mappings:
    - name: BASIC_AUTH_USER
      key: secret/data/jx/adminUser
      property: username
    - name: BASIC_AUTH_PASS
      key: secret/data/jx/adminUser
      property: password

