apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: lighthouse-hmac-token
    backendType: vault
    mappings:
    - name: hmac
      key: secret/data/lighthouse/hmac
      property: token
  - name: lighthouse-oauth-token
    backendType: vault
    mappings:
    - name: oauth
      key: secret/data/jx/pipelineUser
      property: token
  - name: jx-pipeline-git-github-github
    backendType: vault
    mappings:
    - name: username
      key: secret/data/jx/pipelineUser
      property: username
    - name: password
      key: secret/data/jx/pipelineUser
      property: token
  - name: knative-git-user-pass
    backendType: vault
    mappings:
    - name: username
      key: secret/data/jx/pipelineUser
      property: username
    - name: password
      key: secret/data/jx/pipelineUser
      property: token
  - name: nexus
    backendType: vault
    mappings:
    - name: password
      key: secret/data/jx/adminUser
      property: password
  - name: jenkins-x-chartmuseum
    backendType: vault
    mappings:
    - name: BASIC_AUTH_USER
      key: secret/data/jx/adminUser
      property: username
    - name: BASIC_AUTH_PASS
      key: secret/data/jx/adminUser
      property: password
  defaultBackendType: vault

