# Source: vault-instance/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
