# Source: lighthouse/templates/webhooks-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-webhooks
  labels:
    draft: draft-app
    chart: "lighthouse-0.0.633"
    app: lighthouse-webhooks
  annotations:
    checksum/config: e5ef80491082e91444b9aa60e2df6411f4987b6ed3d5d1685fca23ed6eb8c64d
spec:
  replicas: 2
  selector:
    matchLabels:
      draft: draft-app
      app: lighthouse-webhooks
  template:
    metadata:
      labels:
        draft: draft-app
        app: lighthouse-webhooks
    spec:
      serviceAccountName: lighthouse-webhooks
      containers:
      - name: lighthouse-webhooks
        image: gcr.io/jenkinsxio/lighthouse-webhooks:0.0.633
        imagePullPolicy: IfNotPresent
        env:
          - name: "GIT_KIND"
            value: "github"
          - name: "GIT_SERVER"
            value: "https://github.com"
          - name: "GIT_USER"
            value: jenkins-x-labs-bot
          - name: "GIT_TOKEN"
            valueFrom:
              secretKeyRef:
                name: lighthouse-oauth-token
                key: oauth
          - name: "HMAC_TOKEN"
            valueFrom:
              secretKeyRef:
                name: "lighthouse-hmac-token"
                key: hmac
          - name: "JX_LOG_FORMAT"
            value: "json"
          - name: "LOGRUS_FORMAT"
            value: "json"
          - name: JX_DEFAULT_IMAGE
            value: "gcr.io/jenkinsxio-labs-private/jxl:0.0.208"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
